A4 = int(input("Please Enter A4 Price: "))
pen = int(input("Please Enter Pen Price: "))
Inflation = float(input("Please Enter Inflation Rate: "))
Cost = ((pen * 150 * Inflation) / 100) + (A4*50*Inflation/100)
print(f"Extra Cost is {Cost}")
